### ISSUE TITLE
Untranslatable text

### ISSUE THREAD

**Issue by tmaciak** [flores/yet-another-nutrient-calculator#14]
I found one untranslatable string in calculator. When you use "the result of my dose" method and you choose "pumps" as dose unit of measure, the result consist of "pumps" string which ca not be translates as far as I see in i18 files.

Eg. of result (in Polish:)

"Dodanie 6.0 pumps ADA Green Brighty step 2 do Twojego 27.0 L akwarium daje"

**Comment by flores** [comment]
Thanks for that catch @tmaciak.  Looks like the bug affected translations for any units used when calculating the result of a dose.

**Comment by tmaciak** [comment]
Thanks, looks OK., although slightly ungrammatically (plurals ;) ) :)

-----Original Message-----
From: cflores 
[mailto:reply@reply.github.com]
Sent: Thursday, March 15, 2012 5:05 AM
To: tmaciak
Subject: Re: [yet-another-nutrient-calculator] Untranslatable text (#14)

Thanks for that catch @tmaciak.  Looks like the bug affected translations for 
any units used when calculating the result of a dose.

---
