### ISSUE TITLE
Update/edit Easy Life ProFito

### ISSUE THREAD

**Issue by raghauler** [flores/yet-another-nutrient-calculator#24]
GUARANTEED ANALYSIS
Total Nitrogen: 0.03% \* Available Phosphate (P2O5): 0% \* Soluble Potash (K2O): 0.58% \* Iron (Fe): 0.24% \* Magnesium (Mg): 0.09% \* Boron (B): 0.008% \* Copper (Cu): 0.0002% \* Manganese (Mn) : 0.04% \* Molybdenum (Mo): 0.002% \* Zinc (Zn) : 0.002%. Derived from Pentetic Acid, Potassium Sulfate, Ferrous Sulfate, Magnesium Chloride, Boric Acid, Copper Sulfate, Manganese Sulfate, Sodium Molybdate, Zinc Sulfate.

**Comment by flores** [comment]
closed by @raghauler on pull/issue #25

**Comment by raghauler** [comment]
It's been fun helping what little I can with the calculator, but I want to clear up a few things for my peace of mind. I have not given much thought to these things but expect someone else might if given the opportunity.

Just two questions.
The calc asks for the size tank. Does the calculator account for water displacement from the substrate or should I do that?

Concerning plant uptake and concentrations of stuff, is the amount of stuff shown on the graph what is available for the day or what would be left at the end of the day? Example, a daily dose of 4ppm is provided, day 7 shows 3.6ppm of stuff and on day 8 it shows 4ppm of stuff? As I understand it, 3.6ppm of stuff is available by days end and at 90% uptake day 8 has 4ppm of stuff from that days dose at the end of the day. Trivial, I know but I got to know.

**Comment by flores** [comment]
Hey @raghauler / Tug!

The calculator does not account for displacement: it operates as if an input of 20gal is 20gal of water.  I do not think it should account for substrate but maybe we can add something for that (or a range for nutrients is, say, displacement is ~20%).  I think such a flow would be confusing to most folks though?

For the long term model, certain assumptions are made, and so you can kind of think of it as the beginning or end of the day and just use the charts as a way to get an idea of what's going on.

But here's how the calculator does it (top to bottom):

on Day 7, I start with, say 3.6ppm.
The calc checks if there is a water change.  If there is, it deducts that change first and adds back whatever might be in the water supply.  (Let's pretend there isn't).  We're still at 3.6ppm.
The calc checks if we're dosing that day.  If there is, it adds that to the current number.  Let's say we add 4ppm, for a current total of 7.6ppm.
If we're feeding and measuring food input, it adds that next.  Let's say that's not true.  We're still at 7.6ppm.
It then deducts the plant uptake.  In this case it's 90%, or 3.6ppm.  Subtracted from 7.6ppm, we're left with 4ppm.

Does that help?  Again, all this probably won't happen so perfectly in the tank, right?  (Lets say we do the water change at the middle of the photoperiod.  The water change deduction would not be 50% of the previous day's end, but rather 50% at that moment.)  

BUT the real important bit is you can see that numbers and ranges tend to stabilize over time.  This is maybe the real value in the calc.

**Comment by raghauler** [comment]
Hey buddy,
No need to change. The difference is not that great - only a slightly higher concentration of stuff if the actual water displacement is not accounted for per dose. Thank you for clearing this up.

**Comment by raghauler** [comment]
Just thought I would shoot these posts to you for consideration.

http://www.barrreport.com/showthread.php/9676-Micro-Fertilizer-DIY-Formula?p=85466#post85466

http://www.barrreport.com/showthread.php/8848-Question-on-the-composition-of-Plantex-CSM-B
