### ISSUE TITLE
Easy Life Ferro & Flourish Iron

### ISSUE THREAD

**Issue by raghauler** [flores/yet-another-nutrient-calculator#32]
From someone on the Bar report, http://www.barrreport.com/showthread.php/12852-Cautionary-note-on-using-online-nutrient-calculators
"Nutrient Calculator used the information about Easy Life Ferro from the manufacturer's website which turned out to be inaccurate.

I emailed Easy Life about the discrepancy between what was labeled on the bottle and on the website and here's their reply:
"Thank you for your interest in our Easy Life products.
The label on the bottle correct, we have to change the info on our web site."

Easy Life Ferro is the same concentration as Seachem Flourish Iron so using Seachem in the calculator yielded the correct dosage amount.

HOWEVER! if you select Flourish Iron and calculate for EI, you'll get how much you should dose in mL. But if you use that amount to calculate the result of your dose, you'll get an entirely different concentration. E.g. for 10 gallons, dosing EI indicates adding 1 mL to reach .50 ppm of iron. Input this amount in "the result of my dose", you'll get .26ppm, which is half the amount! Which is correct? You'll have to do math to figure it out."

**Comment by raghauler** [comment]
I've emailed Easylife requesting the correct concentration of iron in "Easy Life Ferro". Here is their response, "Ferro contains 10,000 ppm bivalent iron."

The other problem seems to be with the discrepancy between the mL dose the calc suggests for EI and the levels provided when asking the calc for the "result of my dose" when using the recommended EI dose. This seems to be for all of the premixed products and I'm not going to be of much help fixing this.

**Comment by raghauler** [comment]
The "results of my dose," calculations I looked at were accurate. Will someone try their hand at finding a problem. Otherwise, it's all good. 

As for the accuracy of option, "calculating for" a dosing modality. IMO, the programing is this way to avoid confusion though I've not asked.

If the recommend dose is a specific number within a range, using rounded off mL measurements and you account for human nature and common measuring tools - I don't know if the calculator can be more accurate, but can it show the same results in both the "results of my dose," and the "calculating for" options - am I right?

**Comment by flores** [comment]
It sounds like a pretty serious bug and you're right, that doesn't make sense.  I'll have to poke at it and haven't had time quite yet.  Once we take care of it we'll make a new release and I'll update that thread.
